### ISSUE TITLE
Expand the size of output GUI when sort options is called.

### ISSUE THREAD

**Issue by rafflesandrison** [CS2103-AY1819S2-W15-1/main#86]
Sort options will output all the available sorting options.

As the output is really long, I want the output GUI to automatically take up the entire screen so that the user can see all the valid options easily.

![image](https://user-images.githubusercontent.com/12619937/55324744-94933580-54b5-11e9-86bb-676902c62914.png)

**Comment by ReinSheer** [comment]
Done with latest merge
